import { WorkflowPreset } from '@/types/flow';

export const WORKFLOW_PRESETS: WorkflowPreset[] = [
  {
    id: 'customer-support-triage',
    name: 'Customer Support Triage',
    description: 'Classifies customer requests between Billing/Refunds and Technical Bugs or General Help.',
    sampleInput: 'I was charged twice on my credit card for invoice #4092 this month! Please refund the $49 duplicate charge immediately.',
    nodes: [
      {
        id: 'start-1',
        type: 'start',
        position: { x: 300, y: 40 },
        data: {
          label: 'Customer Ticket Ingest',
          description: 'Receives incoming customer email/ticket',
          executionStatus: 'idle',
        },
      },
      {
        id: 'decision-1',
        type: 'decision',
        position: { x: 260, y: 170 },
        data: {
          label: 'Billing Classifier',
          prompt: 'Is this message related to a billing, invoice, payment, or credit card issue?',
          category: 'Billing',
          executionStatus: 'idle',
        },
      },
      {
        id: 'decision-2',
        type: 'decision',
        position: { x: 60, y: 350 },
        data: {
          label: 'Refund Qualifier',
          prompt: 'Does the customer explicitly request a refund, money back, or cancellation of charges?',
          category: 'Refund',
          executionStatus: 'idle',
        },
      },
      {
        id: 'decision-3',
        type: 'decision',
        position: { x: 500, y: 350 },
        data: {
          label: 'Technical Bug Qualifier',
          prompt: 'Is this message reporting a software bug, crash, malfunction, or broken feature?',
          category: 'Technical',
          executionStatus: 'idle',
        },
      },
      {
        id: 'action-1',
        type: 'action',
        position: { x: -30, y: 530 },
        data: {
          label: 'Refund Desk',
          actionType: 'Execute Auto-Refund Approval & Notify Finance',
          executionStatus: 'idle',
        },
      },
      {
        id: 'action-2',
        type: 'action',
        position: { x: 170, y: 530 },
        data: {
          label: 'Billing Specialist',
          actionType: 'Route to Senior Billing Specialist',
          executionStatus: 'idle',
        },
      },
      {
        id: 'action-3',
        type: 'action',
        position: { x: 400, y: 530 },
        data: {
          label: 'Engineering Alert',
          actionType: 'Create P2 Jira Bug & Alert On-Call Engineer',
          executionStatus: 'idle',
        },
      },
      {
        id: 'action-4',
        type: 'action',
        position: { x: 600, y: 530 },
        data: {
          label: 'Self-Serve Help',
          actionType: 'Send Knowledge Base Links & General FAQ',
          executionStatus: 'idle',
        },
      },
    ],
    edges: [
      {
        id: 'e-start-1',
        source: 'start-1',
        target: 'decision-1',
        type: 'decisionEdge',
        data: { condition: 'YES' },
      },
      {
        id: 'e-dec1-yes',
        source: 'decision-1',
        sourceHandle: 'yes',
        target: 'decision-2',
        type: 'decisionEdge',
        data: { condition: 'YES' },
        label: 'YES',
      },
      {
        id: 'e-dec1-no',
        source: 'decision-1',
        sourceHandle: 'no',
        target: 'decision-3',
        type: 'decisionEdge',
        data: { condition: 'NO' },
        label: 'NO',
      },
      {
        id: 'e-dec2-yes',
        source: 'decision-2',
        sourceHandle: 'yes',
        target: 'action-1',
        type: 'decisionEdge',
        data: { condition: 'YES' },
        label: 'YES',
      },
      {
        id: 'e-dec2-no',
        source: 'decision-2',
        sourceHandle: 'no',
        target: 'action-2',
        type: 'decisionEdge',
        data: { condition: 'NO' },
        label: 'NO',
      },
      {
        id: 'e-dec3-yes',
        source: 'decision-3',
        sourceHandle: 'yes',
        target: 'action-3',
        type: 'decisionEdge',
        data: { condition: 'YES' },
        label: 'YES',
      },
      {
        id: 'e-dec3-no',
        source: 'decision-3',
        sourceHandle: 'no',
        target: 'action-4',
        type: 'decisionEdge',
        data: { condition: 'NO' },
        label: 'NO',
      },
    ],
  },
  {
    id: 'content-moderation-gate',
    name: 'Content Moderation Gate',
    description: 'Screen user-submitted comments or posts for abusive language, harassment, or promotional spam.',
    sampleInput: 'Check out this free crypto giveaway at scam-link.fake right now! You can win 1000 BTC!',
    nodes: [
      {
        id: 'start-mod',
        type: 'start',
        position: { x: 280, y: 40 },
        data: {
          label: 'Submission Ingest',
          description: 'Public forum post or comment',
          executionStatus: 'idle',
        },
      },
      {
        id: 'decision-mod-1',
        type: 'decision',
        position: { x: 240, y: 170 },
        data: {
          label: 'Toxic Language Check',
          prompt: 'Does this content contain toxic, abusive, threatening, or hateful speech?',
          category: 'Safety',
          executionStatus: 'idle',
        },
      },
      {
        id: 'decision-mod-2',
        type: 'decision',
        position: { x: 440, y: 350 },
        data: {
          label: 'Spam & Scam Detector',
          prompt: 'Does this content contain suspicious links, crypto scams, or commercial promotional spam?',
          category: 'Spam',
          executionStatus: 'idle',
        },
      },
      {
        id: 'action-mod-ban',
        type: 'action',
        position: { x: 40, y: 350 },
        data: {
          label: 'Ban Account',
          actionType: 'Immediate Post Removal & Suspend User Account',
          executionStatus: 'idle',
        },
      },
      {
        id: 'action-mod-queue',
        type: 'action',
        position: { x: 300, y: 530 },
        data: {
          label: 'Review Queue',
          actionType: 'Quarantine Post & Route to Human Trust & Safety Queue',
          executionStatus: 'idle',
        },
      },
      {
        id: 'action-mod-approve',
        type: 'action',
        position: { x: 580, y: 530 },
        data: {
          label: 'Auto-Approve',
          actionType: 'Approve Submission & Publish to Feed',
          executionStatus: 'idle',
        },
      },
    ],
    edges: [
      {
        id: 'e-mod-start',
        source: 'start-mod',
        target: 'decision-mod-1',
        type: 'decisionEdge',
        data: { condition: 'YES' },
      },
      {
        id: 'e-mod-1-yes',
        source: 'decision-mod-1',
        sourceHandle: 'yes',
        target: 'action-mod-ban',
        type: 'decisionEdge',
        data: { condition: 'YES' },
        label: 'YES',
      },
      {
        id: 'e-mod-1-no',
        source: 'decision-mod-1',
        sourceHandle: 'no',
        target: 'decision-mod-2',
        type: 'decisionEdge',
        data: { condition: 'NO' },
        label: 'NO',
      },
      {
        id: 'e-mod-2-yes',
        source: 'decision-mod-2',
        sourceHandle: 'yes',
        target: 'action-mod-queue',
        type: 'decisionEdge',
        data: { condition: 'YES' },
        label: 'YES',
      },
      {
        id: 'e-mod-2-no',
        source: 'decision-mod-2',
        sourceHandle: 'no',
        target: 'action-mod-approve',
        type: 'decisionEdge',
        data: { condition: 'NO' },
        label: 'NO',
      },
    ],
  },
  {
    id: 'sales-lead-qualification',
    name: 'Sales Lead Qualification',
    description: 'Evaluates inbound sales leads to determine VIP enterprise routing or self-serve onboarding.',
    sampleInput: 'We are a company with 450 engineers looking to purchase an enterprise license plan with dedicated SSO and SLA support.',
    nodes: [
      {
        id: 'start-sales',
        type: 'start',
        position: { x: 280, y: 40 },
        data: {
          label: 'Inbound Contact Form',
          description: 'Demo or pricing inquiry form',
          executionStatus: 'idle',
        },
      },
      {
        id: 'decision-sales-1',
        type: 'decision',
        position: { x: 240, y: 170 },
        data: {
          label: 'Enterprise Size Filter',
          prompt: 'Is this lead requesting enterprise tier, 100+ seats, custom SLA, or single sign-on (SSO)?',
          category: 'Account Size',
          executionStatus: 'idle',
        },
      },
      {
        id: 'decision-sales-2',
        type: 'decision',
        position: { x: 80, y: 350 },
        data: {
          label: 'Urgent Timeline Check',
          prompt: 'Does the lead indicate an immediate purchasing timeline or urgent rollout requirement?',
          category: 'Timeline',
          executionStatus: 'idle',
        },
      },
      {
        id: 'action-sales-vip',
        type: 'action',
        position: { x: -40, y: 530 },
        data: {
          label: 'VIP AE Routing',
          actionType: 'Schedule 30-min Executive Call with VP of Sales',
          executionStatus: 'idle',
        },
      },
      {
        id: 'action-sales-nurture',
        type: 'action',
        position: { x: 180, y: 530 },
        data: {
          label: 'Sales SDR Sequence',
          actionType: 'Assign to Outbound SDR for Custom Demo Walkthrough',
          executionStatus: 'idle',
        },
      },
      {
        id: 'action-sales-selfserve',
        type: 'action',
        position: { x: 440, y: 350 },
        data: {
          label: 'Self-Serve Portal',
          actionType: 'Send 14-day Pro Free Trial & Automated Onboarding Sequence',
          executionStatus: 'idle',
        },
      },
    ],
    edges: [
      {
        id: 'e-sales-start',
        source: 'start-sales',
        target: 'decision-sales-1',
        type: 'decisionEdge',
        data: { condition: 'YES' },
      },
      {
        id: 'e-sales-1-yes',
        source: 'decision-sales-1',
        sourceHandle: 'yes',
        target: 'decision-sales-2',
        type: 'decisionEdge',
        data: { condition: 'YES' },
        label: 'YES',
      },
      {
        id: 'e-sales-1-no',
        source: 'decision-sales-1',
        sourceHandle: 'no',
        target: 'action-sales-selfserve',
        type: 'decisionEdge',
        data: { condition: 'NO' },
        label: 'NO',
      },
      {
        id: 'e-sales-2-yes',
        source: 'decision-sales-2',
        sourceHandle: 'yes',
        target: 'action-sales-vip',
        type: 'decisionEdge',
        data: { condition: 'YES' },
        label: 'YES',
      },
      {
        id: 'e-sales-2-no',
        source: 'decision-sales-2',
        sourceHandle: 'no',
        target: 'action-sales-nurture',
        type: 'decisionEdge',
        data: { condition: 'NO' },
        label: 'NO',
      },
    ],
  },
];
